### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/bet#154]
## Issue
The game freezes after one of the players chooses their seat. The message from the backend just does not reach the frontend. 
This has happened to me multiple times. 

## Steps to reproduce

Please use Vultr nodes for testing.

You might have to repeat the following a few times to make it freeze because it does not freeze all the time.

1. Run 2 player nodes on separate servers
2. Run the dealer node (You can run the dealer first and the player nodes second, I dont think it makes a difference to the outcome)
3. Both player receive `seats` message. Both players request `walletInfo`. Only one of the players receives `walletInfo` response though.
4. Player 1 chooses his seat -> confirmed with the backend -> sits down.
5. Player 2 chooses his seat -> nothing happens. I see the message in the logs from the backend but I do not see it being received on the frontend. (Maybe a socket connectivity issue? 🤷‍♀️ )
6. The last message from the backend log for the node that freezes: `player_lws_write::95::There is more data`

### Player 1
<img width="1792" alt="player1" src="https://user-images.githubusercontent.com/2395326/90458699-353dd000-e153-11ea-94ab-feb7c8ddf01d.png">

#### Terminal log Player 1

[player1.txt](https://github.com/chips-blockchain/bet/files/5087532/player1.txt)

### Player 2 (Frozen node)
<img width="893" alt="player2" src="https://user-images.githubusercontent.com/2395326/90458762-628a7e00-e153-11ea-9a22-5cdee939eca2.png">

#### Terminal log Player 2

[player2.txt](https://github.com/chips-blockchain/bet/files/5087543/player2.txt)

**Comment by piggydoughnut** [comment]
If you look at the end of both logs, it seems like the backend is "blocked" by something or is still processing something and does not send the message to the frontend. 

## Working node:
```
bet_player_wallet_info::1139::{
	"method":	"walletInfo",
	"addr":	"RBHQ88xgPj9vuYKUMfdnCuwRePsqhZva4c",
	"balance":	0.03363323,
	"backend_status":	1,
	"max_players":	2,
	"table_stack_in_chips":	10,
	"table_id":	"2d2a7e52460469feed3f1e7023dc83ffbcabf352509af81ac83a146a75e30e27"
}
lws_callback_http_player::1248::Writing data to the GUI
bet_player_backend::1508::tx_status
bet_player_backend::1508::seats_info_resp
lws_callback_http_player::1248::Writing data to the GUI
```

## Frozen node:
```
bet_player_wallet_info::1139::{
	"method":	"walletInfo",
	"addr":	"bCrYjDLNgY4Vo5roWTsEshLhPd6Rsk8Jg3",
	"balance":	0.02303823,
	"backend_status":	1,
	"max_players":	2,
	"table_stack_in_chips":	10,
	"table_id":	"2d2a7e52460469feed3f1e7023dc83ffbcabf352509af81ac83a146a75e30e27"
}
player_lws_write::95::There is more data
bet_player_backend::1508::seats_info_resp
player_lws_write::95::There is more data
```

**Comment by sg777** [comment]
This issue has been fixed in the recent commits, and we found that we see the game freezes mostly because of the DCV and that happening when we start the dealer without connecting from the GUI.
