### ISSUE TITLE
Dealer node crashes after one hand

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/bet#155]
## Issue
The dealer node crashes with `Segmentation fault (core dumped)` after the first hand. It doesn't matter if the hand is played all the way or one of the players folds.

## Steps to reproduce

Please use Vultr nodes for testing.

1. Run 2 player nodes and one dealer node.
2. Play the first hand. (You can let one of the players fold straight away)
3. DCV fails with `Segmentation fault (core dumped)` after the `finalInfo`

#### Player 1
[player1.txt](https://github.com/chips-blockchain/bet/files/5087650/player1.txt)

#### Player 2
[player2.txt](https://github.com/chips-blockchain/bet/files/5087651/player2.txt)

#### DCV
[dcv.txt](https://github.com/chips-blockchain/bet/files/5087653/dcv.txt)

**Comment by sg777** [comment]
Does this issue is repeating all the time, since I can't be able to reproduce this issue.

**Comment by sg777** [comment]
Closing this issue, as the changes made recently fixing the dealer crashing.
