### ISSUE TITLE
Send the `seats` method with the maxPlayers number of seats

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/bet#157]
We need to let the player choose a seat from the whole table, even though the dealer might be configured for 2 players only.

The GUI needs to receive an array of 9 seats with their occupancy. The players need to be able to seat wherever they want to.

**Comment by sg777** [comment]
The dealer node crash got fixed, there exists some parsing issues at the GUI to do the full testing. Created an issue https://github.com/chips-blockchain/bet/issues/164 for the same.

**Comment by satindergrewal** [comment]
@piggydoughnut I see this issue https://github.com/chips-blockchain/pangea-poker/issues/340#issuecomment-723739427 is resolved and closed in this comment, which is referenced by @sg777.

So, closing this issue. If still unresolved, feel free to re-open it and add more details.
