### ISSUE TITLE
On first execution of "bet" command always crashes complaining about DB and starts fine on second attempt 

### ISSUE THREAD

**Issue by satindergrewal** [chips-blockchain/bet#172]
When executing `bet` command for the first time, it aborts the command and errors about database.

```bash
satinder@cashier1:~/bet/privatebet$ ./bet cashier <IP_HERE>
ln is in sync with chips
sqlite3_init_db_name::36::db_name::/home/satinder/.bet/db/pangea.db
corrupted size vs. prev_size
Aborted
satinder@cashier1:~/bet/privatebet$
```

After this error, when executing the same command next time, the program moves forward with further operations.

There needs to be a condition put in place for relevant part of the code which creates the database if it's already not present, and then proceed with next set of operations.

**Comment by sg777** [comment]
This issue has been fixed.
