### ISSUE TITLE
Issues cross-compiling bet for ARM 32bit and 64bit

### ISSUE THREAD

**Issue by satindergrewal** [chips-blockchain/bet#261]
Trying to cross-compile `bet` for Raspberry Pi arm 32bit having issues.
Following are the commands and attempts done on Ubuntu 18.04:

```bash
sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev \
  libsqlite3-dev python3 net-tools zlib1g-dev libsodium-dev \
  gettext wget libcurl3-gnutls ninja-build libssl-dev \
  libcurl4-gnutls-dev libevent-dev

sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev \
  libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev \
  gettext

sudo apt install tmux qemu-user make unzip

git clone https://github.com/raspberrypi/tools.git

export PATH=$PATH:$(pwd)/tools/arm-bcm2708/arm-linux-gnueabihf/bin

export target_host=arm-linux-gnueabihf

export AR=$target_host-ar
export AS=$target_host-as
export CC=$target_host-gcc
export CXX=$target_host-g++
export LD=$target_host-ld
export STRIP=$target_host-strip


git clone https://github.com/chips-blockchain/bet
cd bet
./configure


satinder@testarm:~/bet$ ./configure
Compiling ccan/tools/configurator/configurator...done
/lib/ld-linux-armhf.so.3: No such file or directory
satinder@testarm:~/bet$

# Searched ld-linux.so.3
satinder@testarm:~/bet$ apt-file search ld-linux.so.3
libc6-armel-cross: /usr/arm-linux-gnueabi/lib/ld-linux.so.3
libc6-armel-cross: /usr/arm-linux-gnueabihf/libsf/ld-linux.so.3
libc6-armhf-cross: /usr/arm-linux-gnueabi/libhf/ld-linux.so.3
libc6-armhf-cross: /usr/arm-linux-gnueabihf/lib/ld-linux.so.3

# Installed libc6-armel-cross
sudo apt-get install libc6-armel-cross

satinder@testarm:~/bet$ ls -lh /usr/arm-linux-gnueabi/lib/ld-linux.so.3
lrwxrwxrwx 1 root root 10 Sep 17  2018 /usr/arm-linux-gnueabi/lib/ld-linux.so.3 -> ld-2.27.so

# Made symnlink
satinder@testarm:~/bet$ sudo ln -sf /usr/arm-linux-gnueabi/lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3
satinder@testarm:~/bet$ ls -lh /lib/ld-linux-armhf.so.3
lrwxrwxrwx 1 root root 40 Sep  5 15:44 /lib/ld-linux-armhf.so.3 -> /usr/arm-linux-gnueabi/lib/ld-linux.so.3
satinder@testarm:~/bet$

# Tried again
satinder@testarm:~/bet$ ./configure
Compiling ccan/tools/configurator/configurator...done
ccan/tools/configurator/configurator: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
satinder@testarm:~/bet$

```

For reference I also followed guide from `c-lightning`: https://github.com/satindergrewal/lightning/blob/grewal/doc/INSTALL.md#to-cross-compile-for-raspberry-pi

**Comment by BlackPeter13** [comment]
> Trying to cross-compile `bet` for Raspberry Pi arm 32bit having issues.
> Following are the commands and attempts done on Ubuntu 18.04:
> 
> ```shell
> sudo apt-get install -y \
>   autoconf automake build-essential git libtool libgmp-dev \
>   libsqlite3-dev python3 net-tools zlib1g-dev libsodium-dev \
>   gettext wget libcurl3-gnutls ninja-build libssl-dev \
>   libcurl4-gnutls-dev libevent-dev
> 
> sudo apt-get install -y \
>   autoconf automake build-essential git libtool libgmp-dev \
>   libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev \
>   gettext
> 
> sudo apt install tmux qemu-user make unzip
> 
> git clone https://github.com/raspberrypi/tools.git
> 
> export PATH=$PATH:$(pwd)/tools/arm-bcm2708/arm-linux-gnueabihf/bin
> 
> export target_host=arm-linux-gnueabihf
> 
> export AR=$target_host-ar
> export AS=$target_host-as
> export CC=$target_host-gcc
> export CXX=$target_host-g++
> export LD=$target_host-ld
> export STRIP=$target_host-strip
> 
> 
> git clone https://github.com/chips-blockchain/bet
> cd bet
> ./configure
> 
> 
> satinder@testarm:~/bet$ ./configure
> Compiling ccan/tools/configurator/configurator...done
> /lib/ld-linux-armhf.so.3: No such file or directory
> satinder@testarm:~/bet$
> 
> # Searched ld-linux.so.3
> satinder@testarm:~/bet$ apt-file search ld-linux.so.3
> libc6-armel-cross: /usr/arm-linux-gnueabi/lib/ld-linux.so.3
> libc6-armel-cross: /usr/arm-linux-gnueabihf/libsf/ld-linux.so.3
> libc6-armhf-cross: /usr/arm-linux-gnueabi/libhf/ld-linux.so.3
> libc6-armhf-cross: /usr/arm-linux-gnueabihf/lib/ld-linux.so.3
> 
> # Installed libc6-armel-cross
> sudo apt-get install libc6-armel-cross
> 
> satinder@testarm:~/bet$ ls -lh /usr/arm-linux-gnueabi/lib/ld-linux.so.3
> lrwxrwxrwx 1 root root 10 Sep 17  2018 /usr/arm-linux-gnueabi/lib/ld-linux.so.3 -> ld-2.27.so
> 
> # Made symnlink
> satinder@testarm:~/bet$ sudo ln -sf /usr/arm-linux-gnueabi/lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3
> satinder@testarm:~/bet$ ls -lh /lib/ld-linux-armhf.so.3
> lrwxrwxrwx 1 root root 40 Sep  5 15:44 /lib/ld-linux-armhf.so.3 -> /usr/arm-linux-gnueabi/lib/ld-linux.so.3
> satinder@testarm:~/bet$
> 
> # Tried again
> satinder@testarm:~/bet$ ./configure
> Compiling ccan/tools/configurator/configurator...done
> ccan/tools/configurator/configurator: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
> satinder@testarm:~/bet$
> ```
> 
> For reference I also followed guide from `c-lightning`: https://github.com/satindergrewal/lightning/blob/grewal/doc/INSTALL.md#to-cross-compile-for-raspberry-pi

Here is my test on rpi,

pi@raspberrypi:~/Desktop/bet $ ./configure
Compiling ccan/tools/configurator/configurator...done
Making autoconf users comfortable... yes
checking for off_t is 32 bits... yes
checking for __alignof__ support... yes
checking for asprintf() declaration... yes
checking for __attribute__((cold)) support... yes
checking for __attribute__((const)) support... yes
checking for __attribute__((deprecated)) support... no
checking for __attribute__((nonnull)) support... yes
checking for __attribute__((sentinel)) support... yes
checking for __attribute__((pure)) support... yes
checking for __attribute__((may_alias)) support... yes
checking for __attribute__((noreturn)) support... yes
checking for __attribute__ format printf support... yes
checking for __attribute__((unused)) support... yes
checking for __attribute__((used)) support... yes
checking for backtrace() in <execinfo.h>... yes
checking for big endian... no
checking for <byteswap.h>... yes
checking for bswap64 in byteswap.h... yes
checking for __builtin_choose_expr support... yes
checking for __builtin_clz support... yes
checking for __builtin_clzl support... yes
checking for __builtin_clzll support... yes
checking for __builtin_ctz support... yes
checking for __builtin_ctzl support... yes
checking for __builtin_ctzll support... yes
checking for __builtin_constant_p support... yes
checking for __builtin_expect support... yes
checking for __builtin_ffs support... yes
checking for __builtin_ffsl support... yes
checking for __builtin_ffsll support... yes
checking for __builtin_popcount support... yes
checking for __builtin_popcountl support... yes
checking for __builtin_popcountll support... yes
checking for __builtin_types_compatible_p support... yes
checking for <intrinsics.h>... no
checking for struct timespec declaration... yes
checking for clock_gettime() declaration... yes
checking for compound literal support... yes
checking for fchdir support... yes
checking for <err.h>... yes
checking for _FILE_OFFSET_BITS to get 64-bit offsets... yes
checking for for loop declaration support... yes
checking for flexible array member support... yes
checking for getpagesize() in <unistd.h>... yes
checking for isblank() in <ctype.h>... yes
checking for little endian... yes
checking for memmem in <string.h>... yes
checking for memrchr in <string.h>... yes
checking for mmap() declaration... yes
checking for /proc/self/maps exists... yes
checking for qsort_r cmp takes trailing arg... yes
checking for __attribute__((section)) and __start/__stop... yes
checking for stack grows upwards... no
checking for statement expression support... yes
checking for <sys/filio.h>... no
checking for <sys/termios.h>... yes
checking for <sys/unistd.h>... yes
checking for __typeof__ support... yes
checking for unaligned access to int... yes
checking for utime() declaration... yes
checking for __attribute__((warn_unused_result))... yes
checking for #pragma omp and -fopenmp support... yes
checking for <valgrind/memcheck.h>... no
checking for working <ucontext.h... yes
checking for passing pointers via makecontext()... yes
checking for __builtin_cpu_supports()... no
checking for sqlite3_expanded_sql... yes
checking for sqlite3... yes
checking for compiler is GCC... yes
checking for GCC version is 7 or above... yes
checking for pwritev() defined... yes
Writing variables to config.vars.21519... yes
Writing header to ccan/config.h... yes
checking for sha256sum... found
Setting PREFIX... /usr/local
Setting CC... arm-linux-gnueabihf-gcc
Setting CONFIGURATOR_CC... arm-linux-gnueabihf-gcc
Setting CWARNFLAGS... -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror
Setting CDEBUGFLAGS... -std=gnu11 -g -fstack-protector
COPTFLAGS not found
SQLITE3_CFLAGS not found
Setting SQLITE3_LDLIBS... -lsqlite3
Setting VALGRIND... 0
Setting COMPAT... 1
Setting STATIC... 0
Setting ASAN... 0
Setting UBSAN... 0
Setting SHA256SUM... sha256sum
Setting FUZZING... 0
pi@raspberrypi:~/Desktop/bet $

**Comment by BlackPeter13** [comment]
pi@raspberrypi:~/Desktop/bet $ ./configure
Compiling ccan/tools/configurator/configurator...done
Making autoconf users comfortable... yes
checking for off_t is 32 bits... yes
checking for __alignof__ support... yes
checking for asprintf() declaration... yes
checking for __attribute__((cold)) support... yes
checking for __attribute__((const)) support... yes
checking for __attribute__((deprecated)) support... no
checking for __attribute__((nonnull)) support... yes
checking for __attribute__((sentinel)) support... yes
checking for __attribute__((pure)) support... yes
checking for __attribute__((may_alias)) support... yes
checking for __attribute__((noreturn)) support... yes
checking for __attribute__ format printf support... yes
checking for __attribute__((unused)) support... yes
checking for __attribute__((used)) support... yes
checking for backtrace() in <execinfo.h>... yes
checking for big endian... no
checking for <byteswap.h>... yes
checking for bswap64 in byteswap.h... yes
checking for __builtin_choose_expr support... yes
checking for __builtin_clz support... yes
checking for __builtin_clzl support... yes
checking for __builtin_clzll support... yes
checking for __builtin_ctz support... yes
checking for __builtin_ctzl support... yes
checking for __builtin_ctzll support... yes
checking for __builtin_constant_p support... yes
checking for __builtin_expect support... yes
checking for __builtin_ffs support... yes
checking for __builtin_ffsl support... yes
checking for __builtin_ffsll support... yes
checking for __builtin_popcount support... yes
checking for __builtin_popcountl support... yes
checking for __builtin_popcountll support... yes
checking for __builtin_types_compatible_p support... yes
checking for <intrinsics.h>... no
checking for struct timespec declaration... yes
checking for clock_gettime() declaration... yes
checking for compound literal support... yes
checking for fchdir support... yes
checking for <err.h>... yes
checking for _FILE_OFFSET_BITS to get 64-bit offsets... yes
checking for for loop declaration support... yes
checking for flexible array member support... yes
checking for getpagesize() in <unistd.h>... yes
checking for isblank() in <ctype.h>... yes
checking for little endian... yes
checking for memmem in <string.h>... yes
checking for memrchr in <string.h>... yes
checking for mmap() declaration... yes
checking for /proc/self/maps exists... yes
checking for qsort_r cmp takes trailing arg... yes
checking for __attribute__((section)) and __start/__stop... yes
checking for stack grows upwards... no
checking for statement expression support... yes
checking for <sys/filio.h>... no
checking for <sys/termios.h>... yes
checking for <sys/unistd.h>... yes
checking for __typeof__ support... yes
checking for unaligned access to int... yes
checking for utime() declaration... yes
checking for __attribute__((warn_unused_result))... yes
checking for #pragma omp and -fopenmp support... yes
checking for <valgrind/memcheck.h>... no
checking for working <ucontext.h... yes
checking for passing pointers via makecontext()... yes
checking for __builtin_cpu_supports()... no
checking for sqlite3_expanded_sql... yes
checking for sqlite3... yes
checking for compiler is GCC... yes
checking for GCC version is 7 or above... yes
checking for pwritev() defined... yes
Writing variables to config.vars.21519... yes
Writing header to ccan/config.h... yes
checking for sha256sum... found
Setting PREFIX... /usr/local
Setting CC... arm-linux-gnueabihf-gcc
Setting CONFIGURATOR_CC... arm-linux-gnueabihf-gcc
Setting CWARNFLAGS... -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror
Setting CDEBUGFLAGS... -std=gnu11 -g -fstack-protector
COPTFLAGS not found
SQLITE3_CFLAGS not found
Setting SQLITE3_LDLIBS... -lsqlite3
Setting VALGRIND... 0
Setting COMPAT... 1
Setting STATIC... 0
Setting ASAN... 0
Setting UBSAN... 0
Setting SHA256SUM... sha256sum
Setting FUZZING... 0
pi@raspberrypi:~/Desktop/bet $

**Comment by BlackPeter13** [comment]
This is my test run of ./configure. "Linux raspberrypi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux"

``pi@raspberrypi:~/Desktop/bet $ ./configure
Compiling ccan/tools/configurator/configurator...done
Making autoconf users comfortable... yes
checking for off_t is 32 bits... yes
checking for __alignof__ support... yes
checking for asprintf() declaration... yes
checking for __attribute__((cold)) support... yes
checking for __attribute__((const)) support... yes
checking for __attribute__((deprecated)) support... no
checking for __attribute__((nonnull)) support... yes
checking for __attribute__((sentinel)) support... yes
checking for __attribute__((pure)) support... yes
checking for __attribute__((may_alias)) support... yes
checking for __attribute__((noreturn)) support... yes
checking for __attribute__ format printf support... yes
checking for __attribute__((unused)) support... yes
checking for __attribute__((used)) support... yes
checking for backtrace() in <execinfo.h>... yes
checking for big endian... no
checking for <byteswap.h>... yes
checking for bswap64 in byteswap.h... yes
checking for __builtin_choose_expr support... yes
checking for __builtin_clz support... yes
checking for __builtin_clzl support... yes
checking for __builtin_clzll support... yes
checking for __builtin_ctz support... yes
checking for __builtin_ctzl support... yes
checking for __builtin_ctzll support... yes
checking for __builtin_constant_p support... yes
checking for __builtin_expect support... yes
checking for __builtin_ffs support... yes
checking for __builtin_ffsl support... yes
checking for __builtin_ffsll support... yes
checking for __builtin_popcount support... yes
checking for __builtin_popcountl support... yes
checking for __builtin_popcountll support... yes
checking for __builtin_types_compatible_p support... yes
checking for <intrinsics.h>... no
checking for struct timespec declaration... yes
checking for clock_gettime() declaration... yes
checking for compound literal support... yes
checking for fchdir support... yes
checking for <err.h>... yes
checking for _FILE_OFFSET_BITS to get 64-bit offsets... yes
checking for for loop declaration support... yes
checking for flexible array member support... yes
checking for getpagesize() in <unistd.h>... yes
checking for isblank() in <ctype.h>... yes
checking for little endian... yes
checking for memmem in <string.h>... yes
checking for memrchr in <string.h>... yes
checking for mmap() declaration... yes
checking for /proc/self/maps exists... yes
checking for qsort_r cmp takes trailing arg... yes
checking for __attribute__((section)) and __start/__stop... yes
checking for stack grows upwards... no
checking for statement expression support... yes
checking for <sys/filio.h>... no
checking for <sys/termios.h>... yes
checking for <sys/unistd.h>... yes
checking for __typeof__ support... yes
checking for unaligned access to int... yes
checking for utime() declaration... yes
checking for __attribute__((warn_unused_result))... yes
checking for #pragma omp and -fopenmp support... yes
checking for <valgrind/memcheck.h>... no
checking for working <ucontext.h... yes
checking for passing pointers via makecontext()... yes
checking for __builtin_cpu_supports()... no
checking for sqlite3_expanded_sql... yes
checking for sqlite3... yes
checking for compiler is GCC... yes
checking for GCC version is 7 or above... yes
checking for pwritev() defined... yes
Writing variables to config.vars.21519... yes
Writing header to ccan/config.h... yes
checking for sha256sum... found
Setting PREFIX... /usr/local
Setting CC... arm-linux-gnueabihf-gcc
Setting CONFIGURATOR_CC... arm-linux-gnueabihf-gcc
Setting CWARNFLAGS... -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror
Setting CDEBUGFLAGS... -std=gnu11 -g -fstack-protector
COPTFLAGS not found
SQLITE3_CFLAGS not found
Setting SQLITE3_LDLIBS... -lsqlite3
Setting VALGRIND... 0
Setting COMPAT... 1
Setting STATIC... 0
Setting ASAN... 0
Setting UBSAN... 0
Setting SHA256SUM... sha256sum
Setting FUZZING... 0
pi@raspberrypi:~/Desktop/bet $ 
``

**Comment by satindergrewal** [comment]
It compiles perfectly fine on Raspberry Pi itself.

The troubles are to cross-compile `bet` on `x86_64` linux machines.

The target is to compile `bet` from Github Actions and it's not Raspberry Pi.

On the Docker side, I already tested the ARM Ubuntu Docker images which compiles `bet` in those containers.

- [arm32v7](https://hub.docker.com/r/arm32v7/ubuntu/) container still fails to compile `bet`.
- [arm64v8](https://hub.docker.com/r/arm64v8/ubuntu/) container compiles `bet` arm64 binary perfectly fine. I yet to push this setup to Github Actions.

See if you resolve 32bit ARM CI/CD issue.

**Comment by satindergrewal** [comment]
Please hold on any efforts to make it cross-compile for now. I need to test something and push update for that in build system.

**Comment by satindergrewal** [comment]
Resolved issue of cross-compiling ARM32 and ARM64 via Docker. I'll be making a CI/CD file update soon.

**Comment by satindergrewal** [comment]
Pushed ARM build scripts with bit of notes in this git commit: https://github.com/chips-blockchain/bet/commit/12404dcc6324ff56bb2e62705c33d1bef491d19b
Next thing will be to try setting up CI/CD.
Might has to make Github Packages for Docker to fasten the process of ARM builds.

**Comment by satindergrewal** [comment]
I tried setting up `aarch64` build in my fork of `bet` to see if Docker aarch64 works via Github Actions. It fails with the following error:

Link: https://github.com/satindergrewal/bet/runs/3610115703?check_suite_focus=true

```bash
Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

Full error log:

```bash
Run ./tools/build_aarch64.sh
Sending build context to Docker daemon   83.5MB

Step 1/6 : FROM arm64v8/ubuntu:16.04
16.04: Pulling from arm64v8/ubuntu
828b35a09f0b: Pulling fs layer
85569e0c1700: Pulling fs layer
a32ca509d288: Pulling fs layer
8168af71f81f: Pulling fs layer
8168af71f81f: Waiting
85569e0c1700: Verifying Checksum
85569e0c1700: Download complete
a32ca509d288: Verifying Checksum
a32ca509d288: Download complete
8168af71f81f: Verifying Checksum
8168af71f81f: Download complete
828b35a09f0b: Verifying Checksum
828b35a09f0b: Download complete
828b35a09f0b: Pull complete
85569e0c1700: Pull complete
a32ca509d288: Pull complete
8168af71f81f: Pull complete
Digest: sha256:11c7a73a8eb322a177481fdeafc34957200f2f0d1f2192044ad5262008d4bba9
Status: Downloaded newer image for arm64v8/ubuntu:16.04
 ---> d6834beb45bf
Step 2/6 : ARG DEBIAN_FRONTEND=noninteractive
Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in d2d5e753c4ce
Removing intermediate container d2d5e753c4ce
 ---> bda417695c85
Step 3/6 : RUN apt-get update && 	DEBIAN_FRONTEND=noninteractive apt-get install -y 	autoconf automake build-essential sudo git libtool libgmp-dev 	libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev 	gettext wget libcurl3-gnutls ninja-build libssl-dev 	libcurl4-gnutls-dev libevent-dev
Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 499e39a8affc
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c apt-get update && 	DEBIAN_FRONTEND=noninteractive apt-get install -y 	autoconf automake build-essential sudo git libtool libgmp-dev 	libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev 	gettext wget libcurl3-gnutls ninja-build libssl-dev 	libcurl4-gnutls-dev libevent-dev' returned a non-zero code: 1
mv: cannot stat 'bet-linux-aarch64-v0.1.3-291-g97458a5.tar.gz': No such file or directory
total 0
```

**Comment by satindergrewal** [comment]
I managed to resolve the following issue with this Stackoverflow solution: https://stackoverflow.com/questions/58298774/standard-init-linux-go211-exec-user-process-caused-exec-format-error/66903309#66903309

> standard_init_linux.go:228: exec user process caused: exec format error

Github Actions did proceeded to compile arm64 binaries, but due to this method using Qemu `aarch64` emulation on `x86_64` architecture, compilation was dead slow. It almost took about ~4.5 hours to complete this compilation!! https://github.com/satindergrewal/bet/actions/runs/1246296524

Tried another solution. Making a self-hosted runner out of Docker installed on my M1 Macbook Pro, and it seems to work in my test. Tried running Docker container on Proxmox server under LXC, but docker had issues running under LXC.

Thought of creating a Qemu-aarch64 VM under Proxmox for self-hosted runner, and in my tests that too takes at least 15+ minutes to complete compilation for `aarch64`, which actually completes in roughly just under 1 minute on my M1 Macbook Pro with Docker `aarch64` container. Pretty sure `arm32` will take hell long time if I tried on Qemu-aarch64 VM.

So, the next test I'll do is to try compiling it on Raspberry Pi, or Odroid XU4, or Rock Pi 4 IoT devices itself, and testing it as a self-hosted runner. Will post updates here after my tests.

**Comment by satindergrewal** [comment]
As expected, self-hosted Raspberry Pi runner for Github Actions been the the fastest solution to building ARM64 builds of `bet`. My latest test shows compiled binaries ready in just about 7 minutes. Reference link: https://github.com/satindergrewal/bet/actions/runs/1251396140

Will be setting up another Raspberry Pi with 32bit OS and will use that for ARM 32bit builds.

**Comment by satindergrewal** [comment]
Implemented ARM64 builds along with MacOS in this git commit: https://github.com/chips-blockchain/bet/commit/4b60de8e73eaa5ed7cbb7e63f036f1d0b0759b3e
