### ISSUE TITLE
remove ccan dependency so windows binaries can be built of bet

### ISSUE THREAD

**Issue by satindergrewal** [chips-blockchain/bet#305]
While setting up Github Action workflow, I tried different methods to make auto-builds of `bet` binaries.

Doing that work and troubleshooting I figured it's `ccan` C library which is one of the causes we can not compile `bet` for windows platform. Because `ccan` is very a collection of various C libraries made for Unix based OSs.

If we are not utilising `ccan` or if we can somehow replace this dependency, please do so.
After that I'll attempt once again to compile `bet` code for windows.

**Comment by satindergrewal** [comment]
Similar to `bet` `c-lightning` is also not compilable for Windows due to `ccan` dependency in `c-lightning` code.

We  should work on porting or adding support of `CHIPS` to [LND](https://github.com/lightningnetwork/lnd) lightning network daemon, which has broad support for different platforms, including iOS and Android mobile.

**Comment by sg777** [comment]
The ccan dependency is removed in this commit. da23a87eb6208033828c6c14f352a9e73f729959
