### ISSUE TITLE
Handling Player Disconnections

### ISSUE THREAD

**Issue by sg777** [chips-blockchain/bet#41]
At this moment if a player gets disconnected during the middle of the game, there is no mechanism to handle this.

**Comment by norbertdragan** [comment]
There is a concept called _Sit Out_ in poker which is activated when a player has to leave the table for some reason - for example, go to the toilet. In this case, hands will not be dealt to this person.

In case of a _cash game_, the blinds will skip this person. If the blinds skip the person, and he returns, he has two choices: 

1. Wait until the it's his turn to place the Big Blind.
2. Place an additional Big Blind during the next round regardless of his position at the table. The player will be able to act similarly to the Big Blind - if there is no raise, the player can check and the betting round continues.

In case of a _tournament_ the player has to place the blinds no matter what and there is no skipping.

Ideally, when a player disconnects, he/she should switch to Sit Out mode. In case of a cash game, after a few rounds of skipping placing the Big Blind, the player person should be removed from the table.

During a tournament, if the player remains disconnected, the blinds will eat their chips.

Poker rooms have some time buffer for a player to reconnect if it happened during a hand and the player had a card.

**Comment by sg777** [comment]
The sitout part has been handled in the latest commits. Now the players can opt to sitout. The player disconnections are handled in a slightly different manner that is when the player gets disconnected then that will be considered as fold and the game continues with the rest of the players.

There isn't any implementation for the player rejoins, it will be handled in https://github.com/chips-blockchain/bet/issues/190.
